openapi: 3.0.1
info:
  title: RestRserve OpenAPI
  version: '1.0'
servers:
  - url: /
paths:
  /api/health/shallow_ping:
    get:
      tags:
        - health:
            name: health
      description: Performs a shallow health ping
      responses:
        200:
          description: API response
          content:
            application/json:
              schema:
                Health:
                  type: string
                  example: 5
  /api/health/deep_ping:
    get:
      tags:
        - health:
            name: health
      description: Performs a deep health ping
      responses:
        200:
          description: API response
          content:
            application/json:
              schema:
                Health:
                  type: string
                  example: "Healthy"
components:
  schemas:
    ShallowPing:
      type: object
      properties:
        Health:
          type: string
          example: "Healthy"
        DateTime:
          type: string
          example: "2021-05-31 20:00:00 EDT"
    ServiceStatus:
      type: object
      properties:
        Health:
          type: string
          example: "Healthy"
        Details:
          type: string
          example: "All dependencies are healthy"
    DeepPing:
      type: object
      properties:
        ShallowPing:
          $ref: '#/components/schemas/ShallowPing'
        ServiceStatus:
          $ref: '#/components/schemas/ServiceStatus'
        Dependencies:
          type: object
          properties:
            ShallowPing:
              $ref: '#/components/schemas/ShallowPing'
            ServiceStatus:
              $ref: '#/components/schemas/ServiceStatus'
            Dependencies:
              $ref: '#/components/schemas/DeepPing'
